---
- name: reload sysctl
  command: sysctl --system

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart rainbow
  ansible.builtin.systemd:
    state: restarted
    name: rainbow
